#spring:
#  application:
#    name: SmartStock
#  datasource:
#    url: jdbc:h2:mem:db_smartstock
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console